### ISSUE TITLE
Synapse API responding 502

### ISSUE THREAD

**Issue by mdfalcon104** [BlazeWasHere/SYN-Explorer-API#2]
Thanks for making the service. The API is always returning 502 error code, could you please fix it? 
https://explorer.dorime.org/api/v1/search/txhash/0x2db3ead3bcd345e9ecb8b022740d2fc1ceb5b4903d36f91c1e4cbaa79e7f3a3a

**Comment by BlazeWasHere** [comment]
up

**Comment by mdfalcon104** [comment]
Thanks for your update
